name: Docker Backend CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    name: Docker build and push image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests.py 

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build backend image
        run: |
          docker build --platform linux --tag mateovalenzuela/apiinversiones:latest .

      - name: Publish backend image to Docker Hub
        run: |
          docker push mateovalenzuela/apiinversiones:latest
